### PR TITLE
Port to humble

### PR DESCRIPTION
**Pull request by Ryanf55**
This has all the changes I made to port to humble. This duplicates other work, however there are unique pieces that can be covered.

### CODE REVIEW

**Comment by Ryanf55** [comment]
> @Ryanf55 Could you switch the base branch of the PR to `https://github.com/ethz-asl/grid_map_geo/tree/ros2` ? Then would be easier for the relevant diff

Done! I'll have to fix merge conflicts now, but it should give you the basic idea.

**Comment by Ryanf55** [comment]
I've fixed merge conflicts. Ready for review.

**Review by Jaeyoung-Lim — APPROVED** [review]
Awesome! Thanks! Looks good for me!

**Comment by Jaeyoung-Lim** [comment]
Realized that the build test of ROS Noetic should not be valid for this branch anymore. Will address in a follow up PR

@Ryanf55 Should we make the ros2 branch the default? or would you prefer a separate repository? I can also create a `grid_map_geo2` under the ASL org if you prefer this way

**Comment by Ryanf55** [comment]
> Realized that the build test of ROS Noetic should not be valid for this branch anymore. Will address in a follow up PR
> 
> @Ryanf55 Should we make the ros2 branch the default? or would you prefer a separate repository? I can also create a `grid_map_geo2` under the ASL org if you prefer this way

I've generally seen just updating `ros2` to be the default. Since the code is largely the same, people still use ROS1, having it all in one repo makes backports easier. I don't have a strong preference.

**Pull request merged**
